# Generated by Django 5.2.3 on 2025-06-24 01:09

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('feedback', 'Feedback'), ('business', 'Business Inquiry'), ('other', 'Other')], db_index=True, default='general', help_text='What type of inquiry is this?', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, help_text="We'll respond to this email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, help_text='Your full name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(db_index=True, help_text='Brief description of your inquiry', max_length=200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='subscribed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_resolved', '-created_at'], name='core_contac_is_reso_c1069a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['category', '-created_at'], name='core_contac_categor_ec7d55_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email', '-created_at'], name='core_contac_email_2e8d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['is_active', '-subscribed_at'], name='core_newsle_is_acti_7bada7_idx'),
        ),
    ]
